### ISSUE TITLE
question

### ISSUE THREAD

**Issue by Otiss-pang** [p-karisani/CEPC#1]
excuse me, an error occured when i use the sample.data, 
Traceback (most recent call last):
```
Traceback (most recent call last):
  File "/home/fzuirdata/anaconda3/envs/pangyifei_py3.7/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/fzuirdata/anaconda3/envs/pangyifei_py3.7/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/fzuirdata/pangyifei/CEPC/src/MainThread.py", line 75, in <module>
    main()
  File "/home/fzuirdata/pangyifei/CEPC/src/MainThread.py", line 69, in main
    device, device_2, args.seed, args.tgt_d, args.src_d, args.cache_dir, args.flag)
  File "/home/fzuirdata/pangyifei/CEPC/src/EDomainAdaptProj.py", line 121, in run
    d_lens, d_max, d_min, d_ave = ELib.get_doc_length_stat(cur_bundle, model_path)
  File "/home/fzuirdata/pangyifei/CEPC/src/ELib.py", line 122, in get_doc_length_stat
    tokenizer = BertTokenizer.from_pretrained(model_path)
  File "/home/fzuirdata/anaconda3/envs/pangyifei_py3.7/lib/python3.7/site-packages/transformers/tokenization_utils_base.py", line 1602, in from_pretrained
    resolved_vocab_files, pretrained_model_name_or_path, init_configuration, *init_inputs, **kwargs
  File "/home/fzuirdata/anaconda3/envs/pangyifei_py3.7/lib/python3.7/site-packages/transformers/tokenization_utils_base.py", line 1674, in _from_pretrained
    tokenizer = cls(*init_inputs, **init_kwargs)
  File "/home/fzuirdata/anaconda3/envs/pangyifei_py3.7/lib/python3.7/site-packages/transformers/tokenization_bert.py", line 194, in __init__
    self.vocab = load_vocab(vocab_file)
  File "/home/fzuirdata/anaconda3/envs/pangyifei_py3.7/lib/python3.7/site-packages/transformers/tokenization_bert.py", line 101, in load_vocab
    tokens = reader.readlines()
  File "/home/fzuirdata/anaconda3/envs/pangyifei_py3.7/lib/python3.7/codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x80 in position 0: invalid start byte

```
What is the cause of the error? Python's version is 3.7.13

**Comment by p-karisani** [comment]
It looks to me that the error is raised by the Transformer API. While loading its files.
Please read this thread and see if it helps: [https://github.com/huggingface/transformers/issues/1620](https://github.com/huggingface/transformers/issues/1620)

**Comment by Otiss-pang** [comment]
> 

thx a lot, the problem has been solved !
